// Fixed output translation: w=z-1, with one output unit equal to the rim radius.
// This is independent of graph pan/zoom and never moves the clock or complex input.
const shiftedClockChoice=document.createElement('label');shiftedClockChoice.innerHTML='<input id="shiftedClock" type="checkbox"> Overlay ζ − 1 on clock';$('planeActions').append(shiftedClockChoice);
const shiftedPathsChoice=document.createElement('label');shiftedPathsChoice.innerHTML='<input id="shiftedClockPaths" type="checkbox" checked> Include shifted sum & product';$('planeActions').append(shiftedPathsChoice);
planeNotes.insertAdjacentHTML('beforeend','<p>Clock overlay: output z is drawn at z−1, with one unit equal to the clock radius. Output 1 is at the axle; output 0 is on the negative-real rim. Thus S₁ and the empty product share the axle, and every ζ zero maps to the same rim point. The pole is unbounded and does not move to the axle. Parts beyond the clock canvas are clipped; this view never rescales to fit.</p>');
let shiftedClockMix=0,shiftedClockLast=performance.now();
const shiftedClockRaster=document.createElement('canvas');shiftedClockRaster.width=shiftedClockRaster.height=W;let shiftedClockCacheKey='',shiftedClockCacheCount=0;
function shiftedClockPoint(z){const c=Math.cos(Math.PI*reflectionMix),a=(1+c)/2,b=-(1-c)/2,dx=R*z[1],dy=-R*(z[0]-1);return [C+a*dx+b*dy,C+b*dx+a*dy];}
function drawShiftedClock(){const now=performance.now(),dt=Math.min(.05,(now-shiftedClockLast)/1000);shiftedClockLast=now;shiftedClockMix+=(Number($('shiftedClock').checked)-shiftedClockMix)*(1-Math.exp(-dt*10));if(shiftedClockMix<.001)return;
 const ctx=g2,current=locusData?.key===locusWanted&&Math.abs(SIGMA-locusData.sigma)<1e-4;
 ctx.save();ctx.globalAlpha=shiftedClockMix;ctx.beginPath();ctx.rect(0,0,W,W);ctx.clip();
 function line(points,colour,width=2,dash=[]){ctx.strokeStyle=colour;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.beginPath();let fresh=true;for(const z of points){if(!z.every(Number.isFinite)){fresh=true;continue;}const p=shiftedClockPoint(z);if(fresh){ctx.moveTo(...p);fresh=false;}else ctx.lineTo(...p);}ctx.stroke();ctx.setLineDash([]);}
 if(current&&$('zetaLocus').checked){const data=locusData.data,key=[locusData.key,reflectionMix.toPrecision(9),$('ghostPaths').checked].join('/'),c=shiftedClockRaster.getContext('2d');if(key!==shiftedClockCacheKey||shiftedClockCacheCount>data.length){c.clearRect(0,0,W,W);shiftedClockCacheCount=0;shiftedClockCacheKey=key;}if(data.length!==shiftedClockCacheCount){for(const ghost of ($('ghostPaths').checked?[true,false]:[false])){c.strokeStyle=ghost?'#e8bd651b':'#e8bd6570';c.lineWidth=1.4;c.beginPath();let fresh=true;for(let i=Math.max(0,shiftedClockCacheCount-3);i<data.length;i+=3){const z=[data[i+1],ghost?-data[i+2]:data[i+2]];if(!z.every(Number.isFinite)){fresh=true;continue;}const p=shiftedClockPoint(z);if(fresh){c.moveTo(...p);fresh=false;}else c.lineTo(...p);}c.stroke();}shiftedClockCacheCount=data.length;}ctx.drawImage(shiftedClockRaster,0,0);}
 if($('shiftedClockPaths').checked){const sum=continuumSum(t,SIGMA,TAUV),prod=eulerPath(t,SIGMA,TAUV);line([...sum.points,sum.z],'#87bff2aa',2);for(let i=1;i<prod.points.length;i++)line([prod.points[i-1].z,prod.points[i].z],'hsla('+hueOf(prod.points[i].p)+' 80% 64% / .65)',2);if(prod.arriving)line([prod.z,prod.arriving],'#bfcbbb88',2,[4,4]);}
 if($('zetaLocus').checked&&liveLocusPreview.sigma===SIGMA&&liveLocusPreview.tau===TAUV){const points=[];let prior=null;for(const q of liveLocusPreview.rows){if(SIGMA===1&&prior&&prior[0]<0&&q[0]>0)points.push([NaN,NaN]);points.push(q.slice(1));prior=q;}line(points,'#ffdfa0',3,current&&locusData.done?[]:[5,4]);}
 const pole=Math.hypot(SIGMA-1,TAUV)<1e-8,z=pole?[Infinity,Infinity]:zeta(SIGMA,TAUV);if(z.every(Number.isFinite)){const p=shiftedClockPoint(z);ctx.fillStyle='#ffdfa0';ctx.beginPath();ctx.arc(...p,5,0,7);ctx.fill();}
 // Two landmarks only. Label outputs, rather than confusing them with input s.
 ctx.font='15px ui-monospace';ctx.textAlign='center';ctx.fillStyle='#f2dfac';for(const [value,label] of [[1,'1'],[0,'0']]){const p=shiftedClockPoint([value,0]);ctx.strokeStyle='#efd5a0';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(...p,6,0,7);ctx.stroke();ctx.fillText(label,p[0],p[1]+24);}ctx.restore();
}
const shiftedClockGuide=updateGuide;updateGuide=function(){shiftedClockGuide();drawShiftedClock();};
